# Generated by Django 4.2.27 on 2026-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='Upload a profile image.', null=True, upload_to='avatars/'),
        ),
    ]
