# Generated by Django 5.2.17 on 2026-08-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile image.', null=True, upload_to='avatars/'),
        ),
    ]
