# Generated by Django 4.2.27 on 2026-01-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('FUNDAMENTALS', 'Fundamentals'), ('STRATEGY', 'Strategy'), ('PSYCHOLOGY', 'Psychology'), ('TUTORIAL', 'Tutorials')], default='FUNDAMENTALS', max_length=50)),
                ('summary', models.TextField(help_text='Brief description for the preview card.')),
                ('content', models.TextField(help_text='HTML content of the article.')),
                ('icon', models.CharField(default='bi-lightbulb', help_text='Bootstrap icon class (ej: bi-graph-up, bi-piggy-bank)', max_length=50)),
                ('read_time_minutes', models.PositiveIntegerField(default=5, verbose_name='Reading time (min)')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['-created_at'],
            },
        ),
    ]
