# Generated by Django 4.2.27 on 2025-12-21 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Asset')),
                ('isin', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISIN')),
                ('category', models.CharField(choices=[('CRYPTO', 'Bitcoin'), ('INDEX_FUND', 'Index Funds'), ('COMMODITY', 'Commodities'), ('STOCK', 'Individual Stocks')], max_length=20, verbose_name='Category')),
                ('platform', models.CharField(max_length=50, verbose_name='Entity/Platform')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('shares', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Shares')),
                ('price_per_share', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Price per Share')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total (€) Invested')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.asset')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Record')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Market Value (€)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='investments.asset')),
            ],
            options={
                'verbose_name': 'Asset History',
                'verbose_name_plural': 'Asset Histories',
                'ordering': ['-date'],
            },
        ),
    ]
