# Generated by Django 4.2.27 on 2025-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('CRYPTO', 'Cryptocurrencies'), ('INDEX_FUND', 'Index Funds'), ('COMMODITY', 'Commodities'), ('STOCK', 'Individual Stocks')], max_length=20, verbose_name='Category'),
        ),
    ]
