# Generated by Django 4.2.27 on 2025-12-23 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0004_alter_asset_user_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asset_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
