# Generated by Django 4.2.27 on 2025-12-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_alter_assethistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_per_share',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='Price per Share'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Shares'),
        ),
    ]
