# Generated by Django 4.2.27 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0007_alter_transaction_price_per_share_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="market_symbol",
            field=models.CharField(
                blank=True,
                help_text="Optional Yahoo Finance symbol used for live market data.",
                max_length=32,
                null=True,
                verbose_name="Market Symbol",
            ),
        ),
    ]
