# Generated by Django 5.2.17 on 2026-08-29 23:34

from django.conf import settings
from django.db import migrations, models


def repair_ownership_and_deduplicate_history(apps, schema_editor):
    transaction_model = apps.get_model("investments", "Transaction")
    history_model = apps.get_model("investments", "AssetHistory")

    for transaction in transaction_model.objects.select_related("asset").iterator():
        if transaction.user_id != transaction.asset.user_id:
            transaction_model.objects.filter(pk=transaction.pk).update(
                user_id=transaction.asset.user_id
            )

    seen = set()
    for history in history_model.objects.select_related("asset").order_by(
        "asset_id", "date", "-id"
    ).iterator():
        key = (history.asset_id, history.date)
        if key in seen:
            history_model.objects.filter(pk=history.pk).delete()
            continue
        seen.add(key)
        if history.user_id != history.asset.user_id:
            history_model.objects.filter(pk=history.pk).update(
                user_id=history.asset.user_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_asset_market_symbol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            repair_ownership_and_deduplicate_history,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='assethistory',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='unique_asset_history_per_date'),
        ),
    ]
