# Generated by Django 5.2.17 on 2026-08-29 23:35

from django.db import migrations, models


def mark_legacy_excluded_assets(apps, schema_editor):
    asset_model = apps.get_model("investments", "Asset")
    asset_model.objects.filter(name="Family Investments").update(
        exclude_from_totals=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_assethistory_unique_asset_history_per_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='exclude_from_totals',
            field=models.BooleanField(default=False, help_text='Exclude this asset from personal portfolio totals and market dashboards.'),
        ),
        migrations.RunPython(mark_legacy_excluded_assets, migrations.RunPython.noop),
    ]
