# Generated by Django 5.2.17 on 2026-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_asset_exclude_from_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethistory',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Market Value'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Invested'),
        ),
    ]
