# Generated by Django 4.2.27 on 2025-12-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_savings_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Savings Target')),
                ('net_worth_target', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Net Worth Target')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target date')),
                ('main_currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='EUR', max_length=3)),
                ('emergency_fund_months', models.IntegerField(default=6, verbose_name='Emergency Fund Months')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
