# Generated by Django 4.2.27 on 2026-01-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monthly Budget'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='retirement_age',
            field=models.PositiveIntegerField(default=65, verbose_name='Retirement Age'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='savings_rate_target',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Savings Rate Target (%)'),
        ),
    ]
