# Generated by Django 4.2.27 on 2026-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_usersettings_monthly_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language_code',
            field=models.CharField(choices=[('en-us', 'English'), ('es', 'Spanish')], default='en-us', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='Europe/Madrid', max_length=64, verbose_name='Time Zone'),
        ),
    ]
