# Generated by Django 4.2.27 on 2026-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_usersettings_language_code_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='financial_profile',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('SECURITY', 'Security First'), ('GROWTH', 'Growth Focus')], default='BALANCED', max_length=12, verbose_name='Financial Profile'),
        ),
    ]
