# Generated by Django 4.2.27 on 2026-02-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_usersettings_financial_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsPotentialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conservative_factor', models.DecimalField(decimal_places=2, default=0.8, max_digits=4, verbose_name='Conservative Factor')),
                ('baseline_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Baseline Factor')),
                ('optimistic_factor', models.DecimalField(decimal_places=2, default=1.2, max_digits=4, verbose_name='Optimistic Factor')),
                ('volatility_impact', models.DecimalField(decimal_places=2, default=0.35, max_digits=4, verbose_name='Volatility Impact')),
                ('emergency_buffer_impact', models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='Emergency Buffer Impact')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_potential_model', to='settings.usersettings')),
            ],
            options={
                'verbose_name': 'Savings Potential Model',
                'verbose_name_plural': 'Savings Potential Models',
            },
        ),
    ]
