# Generated by Django 4.2.27 on 2025-12-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('institution', models.CharField(help_text='e.g., ING, Revolut, Binance...', max_length=100)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings / Emergency Fund'), ('CASH', 'Cash (Wallet)'), ('DEBT', 'Debt / Loan (Liability)')], max_length=20)),
                ('currency', models.CharField(default='EUR', help_text='ISO Code (EUR, USD, etc.)', max_length=3)),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN / Account Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Snapshot Date')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='holdings.bankaccount')),
            ],
            options={
                'verbose_name': 'Balance Snapshot',
                'verbose_name_plural': 'Balance Snapshots',
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
