# Generated by Django 4.2.27 on 2025-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalancesnapshot',
            name='interest_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Interest Earned (Month)'),
        ),
    ]
