# Generated by Django 4.2.27 on 2025-12-23 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdings', '0005_accountbalancesnapshot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalancesnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to=settings.AUTH_USER_MODEL),
        ),
    ]
