# Generated by Django 4.2.27 on 2026-05-16 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holdings', '0006_alter_accountbalancesnapshot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='external_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sync_provider',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('MOCK', 'Mock bank data'), ('GOCARDLESS', 'GoCardless Bank Account Data')], max_length=30)),
                ('institution_id', models.CharField(blank=True, max_length=128)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('agreement_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('LINKED', 'Linked'), ('EXPIRED', 'Expired'), ('ERROR', 'Error')], db_index=True, default='CREATED', max_length=30)),
                ('redirect_url', models.URLField(blank=True)),
                ('consent_url', models.URLField(blank=True)),
                ('accounts', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank connection',
                'verbose_name_plural': 'Bank connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sync_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='holdings.bankconnection'),
        ),
    ]
