# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0007_bankaccount_external_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankconnection",
            name="consent_token",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bankconnection",
            name="provider",
            field=models.CharField(
                choices=[
                    ("MOCK", "Mock bank data"),
                    ("GOCARDLESS", "GoCardless Bank Account Data"),
                    ("YAPILY", "Yapily"),
                ],
                max_length=30,
            ),
        ),
    ]
