# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holdings", "0008_bankconnection_consent_token_and_yapily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankconnection",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name="bankconnection",
            name="consent_url",
            field=models.URLField(blank=True, max_length=4096),
        ),
    ]
