# Generated by Django 4.2.27 on 2025-12-20 20:33

from django.db import migrations

from django.db import migrations

def fix_transaction_signs(apps, schema_editor):
    # Cargamos los modelos desde el registro de la migración
    Transaction = apps.get_model('finances', 'Transaction')
    SubCategory = apps.get_model('finances', 'SubCategory')
    Category = apps.get_model('finances', 'Category')
    
    # Procesamos cada transacción de forma segura
    for tx in Transaction.objects.all():
        try:
            # 1. Obtenemos la subcategoría usando el ID directo
            sub = SubCategory.objects.get(id=tx.subcategory_id)
            
            # 2. Obtenemos la categoría madre
            cat = Category.objects.get(id=sub.parent_category_id)
            
            # 3. Aplicamos la lógica de signos basada en el tipo de categoría
            if cat.transaction_type == 'EXPENSE':
                tx.amount = -abs(tx.amount)
            else:
                tx.amount = abs(tx.amount)
                
            tx.save()
            
        except (SubCategory.DoesNotExist, Category.DoesNotExist):
            # Si falta alguna relación, saltamos para no interrumpir la migración
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_transaction_signs),
    ]


