# Generated by Django 4.2.27 on 2025-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
