# Generated by Django 4.2.27 on 2025-12-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_category_is_essential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_essential',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
    ]
