# Generated by Django 5.2.17 on 2026-08-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_repair_record_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='finances.subcategory'),
        ),
    ]
