DEFAULT_CATEGORY_BLUEPRINTS = [
    {
        "key": "income",
        "name": "Income",
        "transaction_type": "INCOME",
        "expense_type": "N/A",
        "is_housing": False,
        "required": True,
        "subcategories": [
            {"key": "income_salary", "name": "Salary", "is_essential": True},
            {"key": "income_freelance", "name": "Freelance", "is_essential": False},
            {"key": "income_bonus", "name": "Bonus", "is_essential": False},
            {"key": "income_dividends", "name": "Interest & Dividends", "is_essential": False},
            {"key": "income_other", "name": "Other Income", "is_essential": False},
        ],
    },
    {
        "key": "housing",
        "name": "Housing",
        "transaction_type": "EXPENSE",
        "expense_type": "FIXED",
        "is_housing": True,
        "required": False,
        "subcategories": [
            {"key": "housing_rent", "name": "Rent or Mortgage", "is_essential": True},
            {"key": "housing_utilities", "name": "Home Utilities", "is_essential": True},
            {"key": "housing_community", "name": "HOA / Community Fees", "is_essential": False},
            {"key": "housing_insurance", "name": "Home Insurance", "is_essential": False},
            {"key": "housing_maintenance", "name": "Maintenance", "is_essential": False},
        ],
    },
    {
        "key": "food",
        "name": "Food",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "food_grocery", "name": "Groceries", "is_essential": True},
            {"key": "food_restaurants", "name": "Restaurants", "is_essential": False},
            {"key": "food_delivery", "name": "Delivery", "is_essential": False},
            {"key": "food_snacks", "name": "Coffee & Snacks", "is_essential": False},
        ],
    },
    {
        "key": "transport",
        "name": "Transportation",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "transport_fuel", "name": "Fuel", "is_essential": False},
            {"key": "transport_public", "name": "Public Transport", "is_essential": False},
            {"key": "transport_maintenance", "name": "Vehicle Maintenance", "is_essential": False},
            {"key": "transport_tolls", "name": "Parking & Tolls", "is_essential": False},
        ],
    },
    {
        "key": "health",
        "name": "Health",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "health_insurance", "name": "Health Insurance", "is_essential": False},
            {"key": "health_pharmacy", "name": "Pharmacy", "is_essential": False},
            {"key": "health_visits", "name": "Medical Visits & Tests", "is_essential": False},
            {"key": "health_wellness", "name": "Wellness", "is_essential": False},
        ],
    },
    {
        "key": "leisure",
        "name": "Leisure & Subscriptions",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "leisure_streaming", "name": "Streaming", "is_essential": False},
            {"key": "leisure_events", "name": "Events", "is_essential": False},
            {"key": "leisure_hobbies", "name": "Hobbies", "is_essential": False},
            {"key": "leisure_travel", "name": "Travel", "is_essential": False},
        ],
    },
    {
        "key": "education",
        "name": "Education & Development",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "education_books", "name": "Books", "is_essential": False},
            {"key": "education_courses", "name": "Courses", "is_essential": False},
            {"key": "education_tools", "name": "Learning Tools", "is_essential": False},
            {"key": "education_language", "name": "Language Learning", "is_essential": False},
        ],
    },
    {
        "key": "savings",
        "name": "Savings & Investments",
        "transaction_type": "EXPENSE",
        "expense_type": "VARIABLE",
        "is_housing": False,
        "required": False,
        "subcategories": [
            {"key": "savings_emergency", "name": "Emergency Fund", "is_essential": True},
            {"key": "savings_index", "name": "Index Investing", "is_essential": False},
            {"key": "savings_retirement", "name": "Retirement Plan", "is_essential": False},
            {"key": "savings_goals", "name": "Goal-Based Savings", "is_essential": False},
        ],
    },
]


def get_default_category_blueprints():
    return DEFAULT_CATEGORY_BLUEPRINTS
